### ISSUE TITLE
Broken QE-SparqlExecutor component after Apache Jena Update

### ISSUE THREAD

**Issue by MindMaster98** [WDAqua/Qanary-question-answering-components#228]
After updating Apache Jena to 4.7.0 (https://github.com/WDAqua/Qanary-question-answering-components/commit/fbd1ed8e6ab5238a4861b8afa988263e98be4354) the QE-SparqlExecuter doesn't start anymore. While starting the following
error occurs:

```shell
SparqlExecuterComponent                            | 2023-01-23 21:19:21.615 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
SparqlExecuterComponent                            | 
SparqlExecuterComponent                            | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'qanaryComponentDescriptionController' defined in URL [jar:file:/qanary-service.jar!/BOOT-INF/lib/qa.component-3.6.1.jar!/eu/wdaqua/qanary/component/QanaryComponentDescriptionController.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [eu.wdaqua.qanary.component.QanaryComponentDescriptionController]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/jena/system/Vocab
SparqlExecuterComponent                            |    at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:315) ~[spring-beans-5.3.19.jar!/:5.3.19]
SparqlExecuterComponent                            |    at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296) ~[spring-beans-5.3.19.jar!/:5.3.19]
SparqlExecuterComponent                            |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.19.jar!/:5.3.19]
SparqlExecuterComponent                            |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222) ~[spring-beans-5.3.19.jar!/:5.3.19]
SparqlExecuterComponent                            |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.19.jar!/:5.3.19]
SparqlExecuterComponent                            |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.19.jar!/:5.3.19]
SparqlExecuterComponent                            |    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.19.jar!/:5.3.19]
SparqlExecuterComponent                            |    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.19.jar!/:5.3.19]
SparqlExecuterComponent                            |    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.19.jar!/:5.3.19]
SparqlExecuterComponent                            |    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.19.jar!/:5.3.19]
SparqlExecuterComponent                            |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.19.jar!/:5.3.19]
SparqlExecuterComponent                            |    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.19.jar!/:5.3.19]
SparqlExecuterComponent                            |    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.19.jar!/:5.3.19]
SparqlExecuterComponent                            |    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.7.jar!/:2.6.7]
SparqlExecuterComponent                            |    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) ~[spring-boot-2.6.7.jar!/:2.6.7]
SparqlExecuterComponent                            |    at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) ~[spring-boot-2.6.7.jar!/:2.6.7]
SparqlExecuterComponent                            |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-2.6.7.jar!/:2.6.7]
SparqlExecuterComponent                            |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[spring-boot-2.6.7.jar!/:2.6.7]
SparqlExecuterComponent                            |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.7.jar!/:2.6.7]
SparqlExecuterComponent                            |    at eu.wdaqua.qanary.sparqlexecuter.Application.main(Application.java:31) ~[classes!/:3.1.4]
SparqlExecuterComponent                            |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
SparqlExecuterComponent                            |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
SparqlExecuterComponent                            |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
SparqlExecuterComponent                            |    at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
SparqlExecuterComponent                            |    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[qanary-service.jar:3.1.4]
SparqlExecuterComponent                            |    at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[qanary-service.jar:3.1.4]
SparqlExecuterComponent                            |    at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[qanary-service.jar:3.1.4]
SparqlExecuterComponent                            |    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[qanary-service.jar:3.1.4]
SparqlExecuterComponent                            | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [eu.wdaqua.qanary.component.QanaryComponentDescriptionController]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/jena/system/Vocab
SparqlExecuterComponent                            |    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224) ~[spring-beans-5.3.19.jar!/:5.3.19]
SparqlExecuterComponent                            |    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.3.19.jar!/:5.3.19]
SparqlExecuterComponent                            |    at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311) ~[spring-beans-5.3.19.jar!/:5.3.19]
SparqlExecuterComponent                            |    ... 27 common frames omitted
SparqlExecuterComponent                            | Caused by: java.lang.NoClassDefFoundError: org/apache/jena/system/Vocab
SparqlExecuterComponent                            |    at org.apache.jena.tdb.assembler.VocabTDB.<clinit>(VocabTDB.java:34) ~[jena-tdb-4.7.0.jar!/:4.7.0]
SparqlExecuterComponent                            |    at org.apache.jena.tdb.assembler.AssemblerTDB.init(AssemblerTDB.java:25) ~[jena-tdb-4.7.0.jar!/:4.7.0]
SparqlExecuterComponent                            |    at org.apache.jena.tdb.TDB.init(TDB.java:258) ~[jena-tdb-4.7.0.jar!/:4.7.0]
SparqlExecuterComponent                            |    at org.apache.jena.tdb.sys.InitTDB.start(InitTDB.java:29) ~[jena-tdb-4.7.0.jar!/:4.7.0]
SparqlExecuterComponent                            |    at org.apache.jena.base.module.Subsystem.lambda$initialize$2(Subsystem.java:117) ~[jena-base-4.5.0.jar!/:4.5.0]
SparqlExecuterComponent                            |    at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
SparqlExecuterComponent                            |    at org.apache.jena.base.module.Subsystem.forEach(Subsystem.java:193) ~[jena-base-4.5.0.jar!/:4.5.0]
SparqlExecuterComponent                            |    at org.apache.jena.base.module.Subsystem.forEach(Subsystem.java:169) ~[jena-base-4.5.0.jar!/:4.5.0]
SparqlExecuterComponent                            |    at org.apache.jena.base.module.Subsystem.initialize(Subsystem.java:115) ~[jena-base-4.5.0.jar!/:4.5.0]
SparqlExecuterComponent                            |    at org.apache.jena.sys.JenaSystem.init(JenaSystem.java:88) ~[jena-core-4.5.0.jar!/:4.5.0]
SparqlExecuterComponent                            |    at org.apache.jena.riot.RDFDataMgr.<clinit>(RDFDataMgr.java:108) ~[jena-arq-4.5.0.jar!/:4.5.0]
SparqlExecuterComponent                            |    at eu.wdaqua.qanary.component.QanaryComponentDescriptionController.initQanaryServiceDecription(QanaryComponentDescriptionController.java:64) ~[qa.component-3.6.1.jar!/:3.6.1]
SparqlExecuterComponent                            |    at eu.wdaqua.qanary.component.QanaryComponentDescriptionController.<init>(QanaryComponentDescriptionController.java:43) ~[qa.component-3.6.1.jar!/:3.6.1]
SparqlExecuterComponent                            |    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
SparqlExecuterComponent                            |    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[na:na]
SparqlExecuterComponent                            |    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
SparqlExecuterComponent                            |    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[na:na]
SparqlExecuterComponent                            |    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[na:na]
SparqlExecuterComponent                            |    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211) ~[spring-beans-5.3.19.jar!/:5.3.19]
SparqlExecuterComponent                            |    ... 29 common frames omitted
SparqlExecuterComponent                            | Caused by: java.lang.ClassNotFoundException: org.apache.jena.system.Vocab
SparqlExecuterComponent                            |    at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[na:na]
SparqlExecuterComponent                            |    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[na:na]
SparqlExecuterComponent                            |    at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151) ~[qanary-service.jar:3.1.4]
SparqlExecuterComponent                            |    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
SparqlExecuterComponent                            |    ... 48 common frames omitted
SparqlExecuterComponent                            | 

```

The previous versions worked as expected, so the problem seems to be caused by upgrade from Apache Jena 4.6.1 to 4.7.0.
Until this issue is solved, you should roll back the component.

**Comment by anbo-de** [comment]
@MindMaster98 Thanks for pointing me to this problem. For some reason, the semantic versioning is not consistent here.

Rolled back to v4.6.0 in https://github.com/WDAqua/Qanary-question-answering-components/commit/31fa21b5eb3d9635e43a883f514d286fabfcae31#diff-d7b2f0cddc29a2a6d52c6830990a2c93abbcb0ba5ff453ad0fb8715dd1197bc7R17
